### ISSUE TITLE
Error parsing coinbase

### ISSUE THREAD

**Issue by OttoAllmendinger** [0xB10C/bademeister-go#33]
Getting this error when parsing blocks on mainnet:
```
2019/11/26 10:16:21 Error during operation, shutting down: error parsing coinbase: opcode OP_DATA_66 requires 67 bytes, but script only has 18 remaining
```

**Comment by 0xB10C** [comment]
Have had similar problems with parsing coinbase transactions with https://github.com/0xB10C/rawtx. Apparently they can have weird scripts. 

I've used a more manual approach for getting the block height from coinbase tx in mempool.observer:
https://github.com/0xB10C/memo/blob/master/memod/processor/zmq_handler.go#L54-L76. That might be an alternative.

**Comment by OttoAllmendinger** [comment]
thanks, seems to work now
